### ISSUE TITLE
Need for required package versions

### ISSUE THREAD

**Issue by adamoudad** [gudgud96/music-fader-nets#1]
Hi,

Can you please provide a requirements.txt file or a list of package versions working?

I am having issue with installing the required packages. The custom magenta package at https://github.com/gudgud96/magenta/ does not install correctly with `pip install git+https://github.com/gudgud96/magenta/ `. 
```
import magenta
```
outputs it cannot find `magenta` though it is installed. I tried with just `pip install magenta` but then it says it needs `sndfile` library, which outputs errors when I try to install.
My environment uses:
- tensorflow 1.15.5
- pypianoroll 0.5.3
- music21 6.7.2

PS: Concerning my previous error `module 'pypianoroll' has no attribute 'parse'`, it was solved by downgrading to pypianoroll==0.5.3, so I updated this issue and the title.

Best,
Adam.

**Comment by gudgud96** [comment]
Hi adamoudad,

The `magenta` package is not actually a `pip` package. I used it directly as a directory. You can:

(1) clone the repo
(2) bring the `magenta/magenta` up one level to just `magenta/`, so as to import it properly in the code
(3) place the `magenta` repo in the same level of your running code

Let me know if there's anything I can help!

~ Hao
